### ISSUE TITLE
OpenMPI support

### ISSUE THREAD

**Issue by edwardsmith999** [Crompulence/cpl-library#17]
With OpenFOAM repo version based on openMPI and a number of other packages (e.g. Fenics) it is well worth developing this support (also as I think it won't be too much work). The issue will be mostly in the Python and C bindings where the COMMs are defined as different objects.

Problem is in create_comm wrapper, as the OpenMPI COMM handle is not an integer, c_void_p should be used so C bindings needs something like **void" (No idea what to do in the Fortran code, maybe MPI_COMM_f2C required).

**Comment by edu159** [comment]
I think this is a good idea. No need to use void. OpenMPI/MPICH should be selected at compile time (as every code does i.e OpenFOAM) so using pre-processor macros should do it. Python can check an internal library variable which holds the MPI implementation/version  and decide how to use ctypes accordingly.

**Comment by edwardsmith999** [comment]
Your additions all look very sensible, agree with moving to C bindings instead of C++ and adding in the fort subscript on the Fortran code. It looks like f2py is a function in mpi4py 2.0.0 (https://bitbucket.org/mpi4py/mpi4py/src/d8f6a7d2ba8dbbf333d3a2958383f3cd9375cdf0/src/MPI/Comm.pyx#lines-1157), why did you think we needed 3.0.0 or later?

I'm planning to add a line in:

    if StrictVersion(mpi4py.__version__) < StrictVersion('3.0.0'):
        raise mpi4py_version_error("Comm.f2py() and Comm.py2f()" +
                                   " require mpi4py >= 3.0.0")

to check for this, but wonder if we are being too strict here - will 2.0.0 work? The alternative is to support MPICH in the old way for previous versions of mpi4py and not OpenMPI (but this gets messy).

**Comment by edu159** [comment]
Maybe you  are right. This will require more careful assessment I guess. I remember at some point 2.0.0 was causing me an error due to missing function. Anyways looking at the release notes: 

> Release 3.0.2 [2019-06-11]
Bug fixes:
- Fix handling of readonly buffers in support for Python 2 legacy buffer interface. The issue triggers only when using a buffer-like object that is readonly and does not export the new Python 3 buffer interface.
- Fix build issues with Open MPI 4.0.x series related to removal of many MPI-1 symbols deprecated in MPI-2 and removed in MPI-3.
- Minor documentation fixes.

So there might be problems for Open MPI 4.0.x if we not use > 3.0.2 in this case. We could just issue a warning maybe...

**Comment by edwardsmith999** [comment]
Compiles and runs locally with openmpi, still a weird problem running on Actions with failure and no output

**Comment by edwardsmith999** [comment]
This has been implemented and the OpenMPI support seems to work as expected. However, the testing on Github actions still seems to show errors. Closing this issue and will reopen an issue for Actions if can't be fixed
